### PR TITLE
Unlocking wagons for Demonic races, slight fix for not wendigo check

### LINKED ISSUE #1063: Demonic races cannot research wagons in gravity well challenge
The wiki says that the only prerequisite for researching wagons is the wheel technology, however it appears that the secondary housing research (farm houses, lodges, hunting lodges, etc) have to be researched as well for the technology to become available. Since demonic races do not have these housing options available, the wagon technology never shows up.

Here's a save file of balrogs at the beginning of the gravity well challenge. The wheel has been researched, but no option to research wagons has appeared. 
[evolve-2024-02-09-21-26.txt](https://github.com/pmotschmann/Evolve/files/14227924/evolve-2024-02-09-21-26.txt)

### PR DESCRIPTION
**Pull request by saltshaker**
#1075 attempted to fix #1063 by adding a demonic-specific alt unlock for the wagon tech. This did not actually fix the problem because the not wendigo check `!global.race.species === 'wendigo'` is always false due to the not operator being applied to `global.race.species` instead of the boolean result. Switching to a strict inequality fixes this and matches the style of other inequality checks in the file.

### CODE REVIEW

File: src/tech.js [hunk 1]
```diff
@@ -161,7 +161,7 @@ const techs = {
         era: 'civilized',
         reqs: { transport: 1 },
         condition(){
-            return global.tech['farm'] || global.tech['s_lodge'] || (global.tech['hunting'] && global.tech.hunting >= 2) || (global.race['soul_eater'] && !global.race.species === 'wendigo' && global.tech.housing >= 1 && global.tech.currency >= 1) ? true : false;
+            return global.tech['farm'] || global.tech['s_lodge'] || (global.tech['hunting'] && global.tech.hunting >= 2) || (global.race['soul_eater'] && global.race.species !== 'wendigo' && global.tech.housing >= 1 && global.tech.currency >= 1) ? true : false;
```
Comment (Argavyon) [inline src/tech.js:164]: The ternary operator at the end seems unnecessary.
```suggestion
            return global.tech['farm'] || global.tech['s_lodge'] || (global.tech['hunting'] && global.tech.hunting >= 2) || (global.race['soul_eater'] && global.race.species !== 'wendigo' && global.tech.housing >= 1 && global.tech.currency >= 1);
```

**Review by Argavyon — APPROVED** [review]
The fix is correct.

File: src/tech.js (hunk 1 above)
Comment (saltshaker) [reply src/tech.js:164]: I'm inclined to agree, though there are many other tech conditions using the ternary operator in the exact same manner. For example, the governor tech condition:
`return global.genes['governor'] && global.civic.govern.type !== 'anarchy' ? true : false;`
Seems odd to only clean up this instance of it.

Comment (Argavyon) [reply src/tech.js:164]: > Seems odd to only clean up this instance of it.

It's the only instance I've checked. I'd be in favor of fixing any and all of them.
